services:
    iris:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - 41772:1972
        - 42773:52773
      volumes:
        - ./:/home/irisowner/dev
        - ./jdbc:/opt/irisbuild/jdbc

    cache:
      build: 
        context: ./cache
        dockerfile: Dockerfile
      restart: always
      ports:
        - 51972:1972
        - 51772:57772
      volumes:
        - ./:/opt/cacheapp
        
